#spring:
#  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/chat_prototype
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
